version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building Lambda function code..."
      # Add any build commands needed here (e.g., compilation, packaging)
  post_build:
    commands:
      - echo "Deploying Lambda function code..."
      - aws lambda update-function-code --function-name doordash1 --zip-file fileb://lambda_function.zip
